2018-12-06 22:22:42+0800 [-] Log opened.
2018-12-06 22:22:42+0800 [-] EchoFactory starting on 8002
2018-12-06 22:22:42+0800 [-] Starting factory <__main__.EchoFactory object at 0x03846D70>
2018-12-06 22:22:42+0800 [-] Listening....
2018-12-06 22:22:42+0800 [-] 
2018-12-06 22:22:45+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:45+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:45+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:45+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:45+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:45+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:45+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:45+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:45+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:45+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:45+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:45+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:45+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:46+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:46+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:46+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:46+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:47+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:47+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:47+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:47+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:47+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:47+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:47+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:47+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:47+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:47+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:47+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:47+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:47+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:47+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:47+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:47+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:47+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:47+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:47+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:22:47+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:22:47+0800 [-] 'error:tuple index out of range'
2018-12-06 22:22:47+0800 [-] Unhandled error in Deferred:
2018-12-06 22:22:47+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 143, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-06 22:23:47+0800 [-] info:0102030405060708090A0B0C timeout
2018-12-06 22:23:47+0800 [-] info:0102030405060708090A0B0C disconnected
	
2018-12-06 22:30:15+0800 [-] Log opened.
2018-12-06 22:30:15+0800 [-] EchoFactory starting on 8002
2018-12-06 22:30:15+0800 [-] Starting factory <__main__.EchoFactory object at 0x03846DB0>
2018-12-06 22:30:15+0800 [-] Listening....
2018-12-06 22:30:15+0800 [-] 
2018-12-06 22:30:18+0800 [Echo,0,192.168.3.3] info:A11C0102030405060708090A0B0C0304BF9C28F604040000000A5D86
	
2018-12-06 22:30:18+0800 [-] 'error:tuple index out of range'
2018-12-06 22:30:18+0800 [-] "error:'NoneType' object is not iterable"
2018-12-06 22:30:18+0800 [-] Unhandled error in Deferred:
2018-12-06 22:30:18+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "D:\my_app\python3.6\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\development\Plat\Iotserver\server.py", line 188, in get_model_struct
	    AutoDelect(self.model_struct,datastr,sqlconnect)
	  File "D:\development\Plat\Iotserver\AutodelectProtocol\Autodelectprotoctol.py", line 29, in AutoDelect
	    typedict = model_struct['data_type'][datastream[0:2]]
	builtins.KeyError: 'A1'
	
2018-12-06 22:31:18+0800 [-] info:0102030405060708090A0B0C timeout
2018-12-06 22:31:18+0800 [-] info:0102030405060708090A0B0C disconnected
	
